### ISSUE TITLE
referenced_tweets.id.author_id,attachments.media_key  making the JSON file is not valid !

### ISSUE THREAD

**Issue by mnalk** [twitterdev/search-tweets-python#102]
Hello all, I use Twitter API v2 recent search.to scrap 500000 tweets on 09/25/2020, I think there are some updates to this version after I got all the data I want, I was trying to merge all files together to convert them to pandas data frame, I notice that most of the file doesn't look like a JSON file, they are not valid and even when I read them line by line (here is my python code)
df_lines = pd.read_json('finalmerge.json', lines=True) 

I suspect of my fields and I notice that some fields like referenced_tweets.id,referenced_tweets.id.author_id,attachments.media_key are making so much trouble, I have never used JSON before, so is the order matter (I mean when using the order of the command line application) I don't know what is exactly wrong with JSON file and why it's not valid ?. so I have some questions to overcome my challenging to convert these files or to start fresh again? or maybe when I merge files this causes the problem? 

My question as follows 
- should I use the [twitter parser ](https://twitterdev.github.io/tweet_parser/)for the data that I scrap on 09/25/2020 ?  if not how can I fix my files?
-If a scrap a new data today 10/27/2020 , is that mean I have no problem and the version becomes staple?
-If a scrap a new data today 10/27/2020 , I will get a JSON valid file or I have to use Parse tweet? is there a way to incorporate the tweet parser with V2 so I don't have to validate my files?
-What is the best way to merge multiple JSON files in my case?

The command line that I used on 09/25/2020 ?

--query "(diabetes) lang:en" \
--expansions author_id,**referenced_tweets.id**,**referenced_tweets.id.author_id**,**attachments.media_key**s,**entities.mentions.username**,geo.place_id \
--tweet-fields id,created_at,author_id,text,context_annotations,public_metrics,lang,conversation_id,geo \
--user-fields description,username,verified,public_metrics,location,name,created_at \
--place-fields country,full_name,geo,id,name,place_type 

===================================================
I use [parser tweet](https://github.com/twitterdev/tweet_parser/tree/master) to validate my data on 09/25/2020and this is a summary of what I got 

This text has no 'id' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"media_key": "3_1308959379543089152", "type": "photo"}
This text has no 'id' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"media_key": "3_1308959379538935816", "type": "photo"}
This text has no 'id' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"media_key": "3_1309393415889547266", "type": "photo"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"author_id": "715308332", "conversation_id": "1309393421455568898", "created_at": "2020-09-25T07:24:53.000Z", "                                                          text": "RT @DavidJHarrisJr: Soros exposed!\nhttps://t.co/wleIBDfukP", "public_metrics": {"retweet_count": 478, "reply_count": 0, "l                                                          ike_count": 0, "quote_count": 0}, "referenced_tweets": [{"type": "retweeted", "id": "1309387165026209792"}], "entities": {"mentions                                                          ": [{"start": 3, "end": 18, "username": "DavidJHarrisJr"}]}, "id": "1309393421455568898", "lang": "en"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.

This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"text": "@Surisskeptic How is hell a gun? The Jesus follower could stop believing in him and leave they chose t                                                          o believe in his teachings. They chose to believe in hell.", "lang": "en", "created_at": "2020-09-25T06:25:54.000Z", "author_id": "                                                          1250901023415246848", "entities": {"mentions": [{"start": 0, "end": 13, "username": "Surisskeptic"}]}, "public_metrics": {"retweet_                                                          count": 0, "reply_count": 2, "like_count": 0, "quote_count": 0}, "conversation_id": "1309366376759521280", "id": "13093785762282741                                                          76", "referenced_tweets": [{"type": "replied_to", "id": "1309377537122988032"}]}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"context_annotations": [{"domain": {"id": "119", "name": "Holiday", "description": "Holidays like Christmas or Non Tweet payload: {"media_key": "7_1309247721908236288", "type": "video"}
This text has no 'id' key. Use the flag '-t' to pass silently next time.

This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"username": "BTS_twt", "name": "\ubc29\ud0c4\uc18c\ub144\ub2e8", "created_at": "2011-07-14T06:32:56.000Z", "des                                                          cription": "Hi! We are BTS!!", "public_metrics": {"followers_count": 29263212, "following_count": 141, "tweet_count": 12376, "liste                                                          d_count": 71908}, "verified": true, "id": "335141638"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"username": "0ksam_", "name": "samantha", "created_at": "2012-06-30T01:56:16.000Z", "description": "i\u2019m st                                                          raight up not having a good time || uc berkeley || \ud83c\uddf5\ud83c\udded", "public_metrics": {"followers_count": 1031, "followin                                                          g_count": 660, "tweet_count": 47003, "listed_count": 4}, "verified": false, "id": "622414498", "location": "she/her/hers"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"username": "gcambayec", "name": "gabrielle (she/they)", "created_at": "2015-06-09T00:27:55.000Z", "description                                                          ": "#BLM || learn and then learn some more, & that\u2019s how it\u2019s going to go!", "public_metrics": {"followers_count": 353, "                                                          following_count": 430, "tweet_count": 2173, "listed_count": 0}, "verified": false, "id": "3240221184", "location": "Berkeley, CA"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.

Non Tweet payload: {"lang": "en", "text": "@bbibienne Yes, how long is it anyway sjshs", "referenced_tweets": [{"type": "replied_to                                                          ", "id": "1308628281915187200"}], "entities": {"mentions": [{"start": 0, "end": 10, "username": "bbibienne"}]}, "public_metrics": {                                                          "retweet_count": 0, "reply_count": 1, "like_count": 0, "quote_count": 0}, "id": "1309250333021929472", "conversation_id": "13073417                                                          02894505987", "author_id": "845804652134248448", "created_at": "2020-09-24T21:56:18.000Z"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"lang": "en", "text": "wait omg, to the people born between 1994 and 2000 (please don't vote if you were born b                                                          efore 1994 or after 2000), were you taught how to write cursive in school or no? #polls", "public_metrics": {"retweet_count": 1, "r                                                          eply_count": 0, "like_count": 0, "quote_count": 0}, "id": "1307050172795555840", "conversation_id": "1307050172795555840", "author_                                                          id": "1171325937461399552", "created_at": "2020-09-18T20:13:39.000Z"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"lang": "en", "text": "Here comes a powerhouse. 3 top indie artists in this powerful EP by @KarNeVor_Music \nGe                                                          t it blasting. \nCheck it out\n#LGTWO \n\ud83d\udcaa\ud83c\udffb\ud83d\udcaa\ud83c\udffb\ud83d\udcaa\ud83c\udffb\ud83d\udcaa\ud83c\                                                          udffb\ud83d\udd25\ud83d\udd25\ud83d\udd25\ud83d\udd25\ud83d\udcaa\ud83c\udffb\ud83d\udcaa\ud83c\udffb\ud83d\udcaa\ud83c\udffb\ud83d                                                          \udcaa\ud83c\udffb\nhttps://t.co/G53Zt517Dg", "entities": {"mentions": [{"start": 68, "end": 83, "username": "KarNeVor_Music"}]}, "                                                          public_metrics": {"retweet_count": 2, "reply_count": 1, "like_count": 6, "quote_count": 0}, "id": "1309392610872754178", "conversat                                                          ion_id": "1309392610872754178", "author_id": "1154471943539712002", "created_at": "2020-09-25T07:21:40.000Z"}
This text has no 'id' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"media_key": "3_1309095581504212993", "type": "photo"}
This text has no 'id' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"media_key": "3_1309095586914852865", "type": "photo"}
This text has no 'id' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"media_key": "3_1309095592384237569", "type": "photo"}
This text has no 'id' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"media_key": "3_1309095598407274496", "type": "photo"}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
Non Tweet payload: {"text": "RT @_amoafoa_: I made a GoFundMe for my birthday \ud83d\udc49\ud83c\udfff\ud83d\udc48\ud83c\udfff It\u                                                        {"retweet_count": 46, "reply_count": 0, "like_count": 0, "quote_count": 0}}
This dict has no 'user' key. Use the flag '-t' to pass silently next time.
                                                    "}, "entity": {"id": "781974597105094656", "name": "TV/Movies Related"}}, {"domain": {"id": "47", "name": "Brand", "description": "                                                          Brands and Companies"}, "entity": {"id": "1065659570578612224", "name": "BBC", "description": "BBC"}}, {"domain": {"id": "45", "nam                                                          e": "Brand Vertical", "description": "Top level entities that describe a Brands industry"}, "entity": {"id": "781974597310615553",                                                           "name": "Entertainment"}}, {"domain": {"id": "46", "public_metrics": {"retweet_count": 0, "reply_count": 1, "like_count": 1, "quote_count": 0}}

pected object or value. Use the flag '-j' to pass silently next time.
> Bad JSON payload:
>

**Comment by jimmoffitt** [comment]
Hello, 

First, the v2 version does not rely on the TweetParser class. The TweetParser is a tool for handling the two JSON formats that were supported in the 'enterprise' version of the non-v2 search endpoint ("original" and "Activity Stream" formats). 

Since v2 has only one new JSON format, the TweetParser object is not needed to smoothly work with the two older formats. 

Second, another issue was flagged about the client and how it writes out the response JSON. I'll add my response to that issue here as well in the hopes that it helps explain the current output handling:

I would like to better understand the issue you are having. Perhaps we can make some updates to how the client writes out search responses to make it even more flexible.

Currently, when writing responses... If the response has the following form:

{"data": [
  {tweet-object},{tweet-object},{tweet-object} 
],
"includes":{
     "media": [
         {media-object},{media-object},{media-object}
      ],
    "users": [
        {user-object},{user-object}
    ],
    "tweets": [
       {tweet-object}
     ]
  },
 "meta": {meta-object}
}

The client will write out the following content, as "atomic" JSON entities (each line below represents a whole, valid JSON object):
{tweet-object}
{tweet-object}
{tweet-object}
{"media":[ {media-object},{media-object},{media-object}]}
{"users":[ {user-object},{user-object}]}
{"tweets":[ {tweet-object}}
{meta-object}

When taken as together as a whole set, then these objects are not 'packaged' as one valid JSON object. 

As an alternative, there could be an option to write out the entire response as the single JSON object that is received from the endpoint...?

**Comment by mnalk** [comment]
Thank you for your response. Here
<https://drive.google.com/drive/folders/1g8ImmW-AK39-4dPGoV0bZ8dlclYofd11?usp=sharing>is
a sample of my files on Google Drive, I will be giving you access to have
an idea of what I mean. Second I think after merging files what is the best
way to to flat the data frame in Panda. Here are my StackOverflow questions
related to flat the same files here
<https://stackoverflow.com/questions/64456339/how-to-flat-large-data-of-tweets-from-multiped-json-file>
 .

Thank you so much

**Comment by mnalk** [comment]
Thank you Jim Moffitt , any update on what is going on in this nested JSON file?

**Comment by jimmoffitt** [comment]
Hello there. I've been revisiting this project to refresh it for the just-launched /search/all endpoint, which is in support of a new academic research tier of access. https://blog.twitter.com/developer/en_us/topics/tips/2021/enabling-the-future-of-academic-research-with-the-twitter-api.html

So, I assume you stopped using the TweetParser class, and are now attempting to read a search data file into a data frame. Is that right?  Can you share how you have the search client configured with respect to how it writes its output?

One general suggestion is to read the JSON payload into multiple data frames, and then do the "joining" in your Python code. So, you'd have a "data" data frame and an "includes" data frame. 

I'd be interested in other ways you'd like the client to 'write' data. I've been debating teaching the client to generate "atomic" Tweet JSON objects (that are in a JSON array). So the client would take on the task of joining the 'data'  and 'includes' *tables*.  I like the idea of having the object of getting the Tweet payloads that have had the "includes" data injected into it. 

I debate this because I have database schemas already segregate data into "tweets", "users", and "media" entities, so I don't really want the data pre-processed like this if I'm just gonna turn around and undo it.

It would be nice to have the option though... 

It would be amazing to have the client read in some schema and generate the appropriate joins for insertion.

**Comment by igorbrigadir** [comment]
> I've been debating teaching the client to generate "atomic" Tweet JSON objects (that are in a JSON array). So the client would take on the task of joining the 'data' and 'includes' tables. I like the idea of having the object of getting a Tweet object that has had the related "includes" data injected into it.

Just like to second this - this is an appealing idea to have. Currently i'm doing this manually anyway, it would be handy to have this feature.

**Comment by jimmoffitt** [comment]
I am hoping to find time next week to work with the "atomic tweet" code some more. 

I'd be curious to learn more about what output features you'd like to see the client have, and how you manage its output today...

**Comment by jimmoffitt** [comment]
We've made some updates to the search client. It now has update output options, including one that echoes the exact JSON responses from search v2. This will be the complete  {"data":[], "includes":{}, "meta":{}} structure. 

The other important update here is the "atomic Tweet" option that looks up "includes" references and injects those objects into the root Tweet objects, and the client emits one complete Tweet JSON object at a time. If you were to grab multiple Tweets, this entire content would not parse as a valid JSON object since the individual Tweets are not grouped together in a JSON array or other {} structure.

So, perhaps we should ponder an update where each Search payload is translated to the following structure (e.g. no "includes" since those objects have been injected into the root Tweet):

{"data":[
    {atomicTweet},
    {atomicTweet},
    {atomicTweet}
 ],
"meta" {}
}  

@igorbrigadir ^^^^

Closing this using since the default output mode is the JSON API responses, which are complete JSON bodies are not broken into indvidual Tweet objects.
