### ISSUE TITLE
max_tweets parameter mislabelled in V2 docs

### ISSUE THREAD

**Issue by PipGrylls** [twitterdev/search-tweets-python#108]
In the v2 docs when working with results stream the parameter max_tweets is labelled max_results.
[link](https://github.com/twitterdev/search-tweets-python/tree/v2#working-with-the-resultstream)

The `**kwargs` in the `__init__` means this keyword fails silently and RS defaults to 500 tweets.

There is also an argument that the max_tweets parameter is being handled fairly differently to the other parameters. Handling them alongside results_per_call would be preferable unless there is a specific reason it is used differently.

**Comment by jimmoffitt** [comment]
Thank you for pointing this out. When the original enterprise/premium (v1.1) client was retrofitted for v2, there was a decision to untangle some namespace collisions of "max results" being a proxy for both the maximum number of Tweets to pull in a single run (with pagination) and the maximum number of Tweets to return per response... 

And so,  [--max-results MAX_RESULTS] was updated to [--max-tweets MAX_TWEETS], while in the code "max_results" lived on since it is a search API request parameter, and is relabeled to the user as [--results-per-call RESULTS_PER_CALL].

Do you want to submit a PR for the changes you made?

Thanks again.

**Comment by jimmoffitt** [comment]
On second look, leaving the __init__ code (except defaulting to 1000 to avoid **ints** associated with max_results -- 100 with v2, 500 with enterprise/premium): 
 `def __init__(self, endpoint, request_parameters, bearer_token=None, extra_headers_dict=None, max_tweets=1000,
                 max_requests=None, **kwargs):`

pre-v2 code had:
`  # magic number of max tweets if you pass a non_int
        self.max_results = (max_results if isinstance(max_results, int)
                           else 10 ** 15)`
And *that* max_results was the one renamed to max_tweets. 

Clear as mud. 

Closing for now. Feel free to make a pull request.
