### ISSUE TITLE
Update credential doc for clarity and error handling

### ISSUE THREAD

**Issue by binaryaaron** [twitterdev/search-tweets-python#16]
In working with @jimmoffitt, we noticed that credential handling setup is not 100% clear. 

The flexibility introduced by #14 is perhaps not explicit about the defaults values of both the key file (`.twitter_keys.yaml` )and the keys in the file ( `search_tweets_api`  ). 

Also, there is no graceful error when a `KeyError` occurs when parsing the credential file.

**Comment by tonybaloney** [comment]
+1, I'm trying to use this package at the moment, have lots of questions. 
I can see how to setup an app, how to generate a consumer key and secret. But where do I get the bearer token from? Surely the client gets the bearer token for me or that is available in the client? Why would I store a bearer token in the session file, since they normally expire after a short period.

**Comment by binaryaaron** [comment]
@tonybaloney - We are using app-only authentication and the bearer tokens are not delivered with an expiration time. They can be invalidated.

Please see [here](https://developer.twitter.com/en/docs/basics/authentication/overview/application-only) for an overview of the auth method. I am open to putting in a small function to grab a bearer token given your application's keys.

I am about to update the credentialing docs. If there is anything not clear on there, feel free to let me know.

**Comment by tonybaloney** [comment]
I'll raise a PR to allow the user to put the consumer key and secret into the yaml file, having to manually generate bearer tokens is going to frustrate to anyone who doesn't know Oauth2 intimately. It's not obvious from the twitter docs which endpoint to call to get the bearer token as well.
