### ISSUE TITLE
Add a log message to indicate endpoint switch to the user

### ISSUE THREAD

**Issue by jrmontag** [twitterdev/search-tweets-python#51]
The `ResultStream` constructor selects the `/counts` or `/search` endpoint by reading the json rule payload and checking to see if there is a `bucket` key, ([here](https://github.com/twitterdev/search-tweets-python/blob/c1453961e0f9ad3942098b9d4952f9019e3ecc3e/searchtweets/result_stream.py#L188))

While convenient, this switch can also be confusing to the user. I'd like to propose a logging message if the endpoint is swapped. Perhaps a `logging.warning` so that it shows in a Jupyter notebook.

Thoughts?

**Comment by binaryaaron** [comment]
I'd welcome any simplification there; I wrote that a long time ago and haven't examined it much since IIRC. I'm curious about the case when it's switched; the API requires an explicit change to use the counts endpoint. Have you seen a case when this switch happens unexpectedly? If so, we should for sure fix that.

**Comment by jimmoffitt** [comment]
Seems the user has full control over which endpoint is hit, via the --count-bucket parameter.
