### ISSUE TITLE
results_per_call defaults to 100, not 500 as stated in the docs

### ISSUE THREAD

**Issue by caph1993** [twitterdev/search-tweets-python#70]
I ran a `collect_results` query without setting the parameter `results_per_call` using a premium (and non-sandbox) endpoint, which supports 500 tweets per request. The docs say `results_per_call` defaults to the maximum allowed, which is 500.

`max_results` was set to 2500, thus I expected 5 (or at most 6) requests. But according to my twitter dashboard, 26 requests where used. I guess this corresponds to 2500/100=25 approx.

**Comment by jrmontag** [comment]
Hi @caph1993, thanks for opening an issue. Can you please include some other information for debugging purposes? 
- library version
- OS and python version 
- the command you ran when observing this issue

Note that requests aren't guaranteed to include the max 500 activities because pagination occurs over both activity count and time (30 days).

**Comment by jimmoffitt** [comment]
Client and endpoint now both default to 100 for --results-per-call/max_results.

If you want to maximum Tweets per request, use --results-per-call 500.

Docs for --results-per-call state it defaults to 100:

--results-per-call RESULTS_PER_CALL
                        Number of results to return per call (default 100; max
                        500) - corresponds to 'maxResults' in the API. If making a 'counts' request with '--count-bucket', this parameter is ignored.
